//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annual_Report
    {
        public int annual_report_id { get; set; }
        public string fileName { get; set; }
        public string year { get; set; }
        public byte[] cover_image { get; set; }
    }
}
