//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public long appeal_id { get; set; }
        public string title { get; set; }
        public string meta_data { get; set; }
        public string content { get; set; }
        public string author { get; set; }
        public string country { get; set; }
        public System.DateTime publication_date { get; set; }
        public string header_picture_path { get; set; }
        public string content_picture1_path { get; set; }
        public string content_picture2_path { get; set; }
        public string status { get; set; }
        public int amount1 { get; set; }
        public int amount2 { get; set; }
        public int amount3 { get; set; }
        public string amount1Message { get; set; }
        public string amount2Message { get; set; }
        public string amount3Message { get; set; }
        public string contentImage1Note { get; set; }
        public string contentImage2Note { get; set; }
    }
}
