//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateVolunteer
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string gender { get; set; }
        public string birthday { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string emergencyContactName { get; set; }
        public string contactNumber { get; set; }
    }
}
