//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public long donation_id { get; set; }
        public string donation_type { get; set; }
        public string project_name { get; set; }
        public long amount { get; set; }
        public string donor_firstname { get; set; }
        public string donor_surname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string taxpayer { get; set; }
        public string customerID { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string remarks { get; set; }
    }
}
