//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMEntities : DbContext
    {
        public HRMEntities()
            : base("name=HRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annual_Report> Annual_Report { get; set; }
        public virtual DbSet<Appeal> Appeals { get; set; }
        public virtual DbSet<CandidateVolunteer> CandidateVolunteers { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<PriceAmount> PriceAmounts { get; set; }
        public virtual DbSet<SlideShow> SlideShows { get; set; }
        public virtual DbSet<StripeCustomerId> StripeCustomerIds { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
    }
}
