//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int policy_id { get; set; }
        public string policy_name { get; set; }
        public string fileName { get; set; }
        public string file_type { get; set; }
        public string file_size { get; set; }
        public int pages { get; set; }
    }
}
